"""
PRAVAHA — Regional River-Basin Monitoring Nodes
49 high-vulnerability stations across the Himalaya, North Indian flood corridors,
Western Ghats, and North-East hill tracts.
"""

from typing import Dict, List, Any

REGIONS: List[Dict[str, Any]] = [
    # ---- 1. Uttarakhand (Himalayan Headwaters) ----
    {
        "id": "kedarnath-rudraprayag",
        "name": "Kedarnath / Rudraprayag",
        "state": "Uttarakhand",
        "river_basin": "Ganga Basin",
        "river_name": "Mandakini River",
        "lat": 30.7346,
        "lon": 79.0669,
        "catchment_area_km2": 1420.0,
        "slope_deg": 38.5,
        "mean_elevation_m": 3584.0,
        "drainage_density": 3.4,
        "forest_cover_pct": 34.0,
        "bankfull_discharge_m3s": 850.0,
        "warning_level_m": 4.5,
        "danger_level_m": 6.2,
        "dam_upstream": None,
        "glacier_fed": True,
        "vulnerable_villages": 42,
        "population_at_risk": 38500,
    },
    {
        "id": "uttarkashi-bhagirathi",
        "name": "Uttarkashi",
        "state": "Uttarakhand",
        "river_basin": "Ganga Basin",
        "river_name": "Bhagirathi River",
        "lat": 30.7268,
        "lon": 78.4354,
        "catchment_area_km2": 4680.0,
        "slope_deg": 35.2,
        "mean_elevation_m": 2980.0,
        "drainage_density": 3.1,
        "forest_cover_pct": 42.0,
        "bankfull_discharge_m3s": 1400.0,
        "warning_level_m": 5.8,
        "danger_level_m": 7.5,
        "dam_upstream": {
            "name": "Maneri Bhali Stage-II",
            "rule_curve_threshold": 85.0,
            "capacity_mcm": 4.8,
            "current_storage_pct": 74.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 56,
        "population_at_risk": 52000,
    },
    {
        "id": "chamoli-joshimath",
        "name": "Chamoli / Joshimath",
        "state": "Uttarakhand",
        "river_basin": "Ganga Basin",
        "river_name": "Alaknanda / Dhauliganga",
        "lat": 30.5562,
        "lon": 79.5674,
        "catchment_area_km2": 4250.0,
        "slope_deg": 41.0,
        "mean_elevation_m": 3120.0,
        "drainage_density": 3.5,
        "forest_cover_pct": 31.0,
        "bankfull_discharge_m3s": 1250.0,
        "warning_level_m": 5.2,
        "danger_level_m": 7.0,
        "dam_upstream": {
            "name": "Tapovan Vishnugad",
            "rule_curve_threshold": 80.0,
            "capacity_mcm": 3.5,
            "current_storage_pct": 68.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 48,
        "population_at_risk": 44000,
    },
    {
        "id": "tehri-garhwali",
        "name": "Tehri / Bhagirathi Gorge",
        "state": "Uttarakhand",
        "river_basin": "Ganga Basin",
        "river_name": "Bhagirathi / Tehri Reservoir",
        "lat": 30.3782,
        "lon": 78.4803,
        "catchment_area_km2": 7511.0,
        "slope_deg": 29.0,
        "mean_elevation_m": 2200.0,
        "drainage_density": 2.7,
        "forest_cover_pct": 48.0,
        "bankfull_discharge_m3s": 3200.0,
        "warning_level_m": 8.0,
        "danger_level_m": 10.5,
        "dam_upstream": {
            "name": "Tehri Dam (Asia's Highest)",
            "rule_curve_threshold": 92.0,
            "capacity_mcm": 3540.0,
            "current_storage_pct": 86.5,
        },
        "glacier_fed": True,
        "vulnerable_villages": 65,
        "population_at_risk": 95000,
    },
    {
        "id": "pithoragarh-dharchula",
        "name": "Pithoragarh / Dharchula",
        "state": "Uttarakhand",
        "river_basin": "Ganga Basin",
        "river_name": "Kali River",
        "lat": 29.8475,
        "lon": 80.5369,
        "catchment_area_km2": 3890.0,
        "slope_deg": 37.0,
        "mean_elevation_m": 2750.0,
        "drainage_density": 3.2,
        "forest_cover_pct": 39.0,
        "bankfull_discharge_m3s": 1100.0,
        "warning_level_m": 5.0,
        "danger_level_m": 6.8,
        "dam_upstream": {
            "name": "Dhauliganga Dam",
            "rule_curve_threshold": 88.0,
            "capacity_mcm": 6.2,
            "current_storage_pct": 79.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 38,
        "population_at_risk": 36000,
    },
    {
        "id": "dehradun-rishikesh",
        "name": "Rishikesh / Dehradun Foothills",
        "state": "Uttarakhand",
        "river_basin": "Ganga Basin",
        "river_name": "Ganga / Song River",
        "lat": 30.1033,
        "lon": 78.2947,
        "catchment_area_km2": 21800.0,
        "slope_deg": 18.5,
        "mean_elevation_m": 850.0,
        "drainage_density": 2.2,
        "forest_cover_pct": 55.0,
        "bankfull_discharge_m3s": 5500.0,
        "warning_level_m": 7.2,
        "danger_level_m": 9.4,
        "dam_upstream": None,
        "glacier_fed": True,
        "vulnerable_villages": 72,
        "population_at_risk": 180000,
    },
    {
        "id": "nainital-haldwani",
        "name": "Nainital / Haldwani",
        "state": "Uttarakhand",
        "river_basin": "Ganga Basin",
        "river_name": "Gaula River",
        "lat": 29.3803,
        "lon": 79.4636,
        "catchment_area_km2": 1100.0,
        "slope_deg": 31.0,
        "mean_elevation_m": 1450.0,
        "drainage_density": 2.9,
        "forest_cover_pct": 58.0,
        "bankfull_discharge_m3s": 720.0,
        "warning_level_m": 4.2,
        "danger_level_m": 5.8,
        "dam_upstream": {
            "name": "Gaula Barrage",
            "rule_curve_threshold": 82.0,
            "capacity_mcm": 2.1,
            "current_storage_pct": 65.0,
        },
        "glacier_fed": False,
        "vulnerable_villages": 35,
        "population_at_risk": 110000,
    },
    {
        "id": "haridwar-plains",
        "name": "Haridwar (Ganga Gorge Exit)",
        "state": "Uttarakhand",
        "river_basin": "Ganga Basin",
        "river_name": "Ganga River",
        "lat": 29.9457,
        "lon": 78.1642,
        "catchment_area_km2": 23500.0,
        "slope_deg": 8.0,
        "mean_elevation_m": 314.0,
        "drainage_density": 1.8,
        "forest_cover_pct": 32.0,
        "bankfull_discharge_m3s": 7500.0,
        "warning_level_m": 8.5,
        "danger_level_m": 11.0,
        "dam_upstream": {
            "name": "Bhimgauda Barrage",
            "rule_curve_threshold": 90.0,
            "capacity_mcm": 15.0,
            "current_storage_pct": 81.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 88,
        "population_at_risk": 260000,
    },

    # ---- 2. Himachal Pradesh (Upper Indus & Beas Basins) ----
    {
        "id": "mandi-beas",
        "name": "Mandi (Beas Gorge)",
        "state": "Himachal Pradesh",
        "river_basin": "Indus / Beas Basin",
        "river_name": "Beas River / Suketi Khad",
        "lat": 31.7087,
        "lon": 76.9320,
        "catchment_area_km2": 5260.0,
        "slope_deg": 34.0,
        "mean_elevation_m": 1750.0,
        "drainage_density": 3.2,
        "forest_cover_pct": 46.0,
        "bankfull_discharge_m3s": 1650.0,
        "warning_level_m": 5.5,
        "danger_level_m": 7.4,
        "dam_upstream": {
            "name": "Pandoh Dam",
            "rule_curve_threshold": 86.0,
            "capacity_mcm": 41.0,
            "current_storage_pct": 89.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 58,
        "population_at_risk": 78000,
    },
    {
        "id": "kullu-manali",
        "name": "Kullu / Manali Valley",
        "state": "Himachal Pradesh",
        "river_basin": "Indus / Beas Basin",
        "river_name": "Upper Beas / Parbati River",
        "lat": 31.9579,
        "lon": 77.1095,
        "catchment_area_km2": 3200.0,
        "slope_deg": 39.0,
        "mean_elevation_m": 2450.0,
        "drainage_density": 3.6,
        "forest_cover_pct": 51.0,
        "bankfull_discharge_m3s": 1150.0,
        "warning_level_m": 4.8,
        "danger_level_m": 6.5,
        "dam_upstream": {
            "name": "Larji Dam",
            "rule_curve_threshold": 84.0,
            "capacity_mcm": 11.0,
            "current_storage_pct": 77.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 46,
        "population_at_risk": 64000,
    },
    {
        "id": "shimla-rampur",
        "name": "Rampur / Shimla Inner Hills",
        "state": "Himachal Pradesh",
        "river_basin": "Indus / Sutlej Basin",
        "river_name": "Sutlej River",
        "lat": 31.4502,
        "lon": 77.6322,
        "catchment_area_km2": 49800.0,
        "slope_deg": 32.5,
        "mean_elevation_m": 2100.0,
        "drainage_density": 2.8,
        "forest_cover_pct": 38.0,
        "bankfull_discharge_m3s": 3100.0,
        "warning_level_m": 6.8,
        "danger_level_m": 8.9,
        "dam_upstream": {
            "name": "Nathpa Jhakri HEP (1500 MW)",
            "rule_curve_threshold": 88.0,
            "capacity_mcm": 3.4,
            "current_storage_pct": 82.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 62,
        "population_at_risk": 82000,
    },
    {
        "id": "kangra-dharamshala",
        "name": "Kangra / Dharamshala",
        "state": "Himachal Pradesh",
        "river_basin": "Indus / Beas Basin",
        "river_name": "Neugal / Baner Khad",
        "lat": 32.0998,
        "lon": 76.2691,
        "catchment_area_km2": 2400.0,
        "slope_deg": 33.0,
        "mean_elevation_m": 1500.0,
        "drainage_density": 3.3,
        "forest_cover_pct": 47.0,
        "bankfull_discharge_m3s": 980.0,
        "warning_level_m": 4.4,
        "danger_level_m": 6.0,
        "dam_upstream": None,
        "glacier_fed": True,
        "vulnerable_villages": 49,
        "population_at_risk": 91000,
    },
    {
        "id": "chamba-ravi",
        "name": "Chamba / Ravi Gorge",
        "state": "Himachal Pradesh",
        "river_basin": "Indus / Ravi Basin",
        "river_name": "Ravi River",
        "lat": 32.5534,
        "lon": 76.1258,
        "catchment_area_km2": 5100.0,
        "slope_deg": 36.0,
        "mean_elevation_m": 2200.0,
        "drainage_density": 3.0,
        "forest_cover_pct": 43.0,
        "bankfull_discharge_m3s": 1500.0,
        "warning_level_m": 5.4,
        "danger_level_m": 7.2,
        "dam_upstream": {
            "name": "Chamera Stage-I",
            "rule_curve_threshold": 90.0,
            "capacity_mcm": 391.0,
            "current_storage_pct": 84.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 53,
        "population_at_risk": 68000,
    },
    {
        "id": "kinnaur-sangla",
        "name": "Kinnaur / Sangla Valley",
        "state": "Himachal Pradesh",
        "river_basin": "Indus / Sutlej Basin",
        "river_name": "Baspa River",
        "lat": 31.4239,
        "lon": 78.2570,
        "catchment_area_km2": 1950.0,
        "slope_deg": 42.0,
        "mean_elevation_m": 3400.0,
        "drainage_density": 3.7,
        "forest_cover_pct": 28.0,
        "bankfull_discharge_m3s": 650.0,
        "warning_level_m": 3.8,
        "danger_level_m": 5.2,
        "dam_upstream": {
            "name": "Baspa-II HEP",
            "rule_curve_threshold": 85.0,
            "capacity_mcm": 1.2,
            "current_storage_pct": 73.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 24,
        "population_at_risk": 19500,
    },
    {
        "id": "lahaul-spiti",
        "name": "Lahaul (Chandra-Bhaga)",
        "state": "Himachal Pradesh",
        "river_basin": "Indus / Chenab Basin",
        "river_name": "Chandra / Bhaga River",
        "lat": 32.5714,
        "lon": 77.0319,
        "catchment_area_km2": 7600.0,
        "slope_deg": 37.0,
        "mean_elevation_m": 3900.0,
        "drainage_density": 2.9,
        "forest_cover_pct": 6.0,
        "bankfull_discharge_m3s": 1050.0,
        "warning_level_m": 4.6,
        "danger_level_m": 6.2,
        "dam_upstream": None,
        "glacier_fed": True,
        "vulnerable_villages": 18,
        "population_at_risk": 14000,
    },
    {
        "id": "sirmaur-paonta",
        "name": "Sirmaur / Paonta Sahib",
        "state": "Himachal Pradesh",
        "river_basin": "Ganga / Yamuna Basin",
        "river_name": "Giri / Yamuna River",
        "lat": 30.4394,
        "lon": 77.6247,
        "catchment_area_km2": 2600.0,
        "slope_deg": 22.0,
        "mean_elevation_m": 720.0,
        "drainage_density": 2.4,
        "forest_cover_pct": 49.0,
        "bankfull_discharge_m3s": 1200.0,
        "warning_level_m": 4.9,
        "danger_level_m": 6.7,
        "dam_upstream": {
            "name": "Renukaji Dam",
            "rule_curve_threshold": 80.0,
            "capacity_mcm": 498.0,
            "current_storage_pct": 62.0,
        },
        "glacier_fed": False,
        "vulnerable_villages": 42,
        "population_at_risk": 67000,
    },

    # ---- 3. Jammu & Kashmir and Ladakh ----
    {
        "id": "srinagar-jhelum",
        "name": "Srinagar (Ram Munshi Bagh)",
        "state": "Jammu & Kashmir",
        "river_basin": "Indus / Jhelum Basin",
        "river_name": "Jhelum River",
        "lat": 34.0734,
        "lon": 74.8214,
        "catchment_area_km2": 11200.0,
        "slope_deg": 14.0,
        "mean_elevation_m": 1620.0,
        "drainage_density": 2.1,
        "forest_cover_pct": 36.0,
        "bankfull_discharge_m3s": 1200.0,
        "warning_level_m": 5.5,
        "danger_level_m": 6.7,
        "dam_upstream": None,
        "glacier_fed": True,
        "vulnerable_villages": 84,
        "population_at_risk": 450000,
    },
    {
        "id": "anantnag-sangam",
        "name": "Sangam / Anantnag",
        "state": "Jammu & Kashmir",
        "river_basin": "Indus / Jhelum Basin",
        "river_name": "Upper Jhelum / Lidder",
        "lat": 33.7845,
        "lon": 75.0934,
        "catchment_area_km2": 5800.0,
        "slope_deg": 28.0,
        "mean_elevation_m": 1950.0,
        "drainage_density": 2.7,
        "forest_cover_pct": 42.0,
        "bankfull_discharge_m3s": 950.0,
        "warning_level_m": 6.4,
        "danger_level_m": 7.6,
        "dam_upstream": None,
        "glacier_fed": True,
        "vulnerable_villages": 61,
        "population_at_risk": 135000,
    },
    {
        "id": "baramulla-asham",
        "name": "Baramulla / Asham",
        "state": "Jammu & Kashmir",
        "river_basin": "Indus / Jhelum Basin",
        "river_name": "Lower Jhelum / Wular Outflow",
        "lat": 34.2093,
        "lon": 74.3436,
        "catchment_area_km2": 15300.0,
        "slope_deg": 16.0,
        "mean_elevation_m": 1580.0,
        "drainage_density": 2.0,
        "forest_cover_pct": 33.0,
        "bankfull_discharge_m3s": 1450.0,
        "warning_level_m": 4.8,
        "danger_level_m": 6.0,
        "dam_upstream": {
            "name": "Uri-I Barrage",
            "rule_curve_threshold": 85.0,
            "capacity_mcm": 15.0,
            "current_storage_pct": 71.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 55,
        "population_at_risk": 160000,
    },
    {
        "id": "doda-chenab",
        "name": "Doda / Chenab Valley",
        "state": "Jammu & Kashmir",
        "river_basin": "Indus / Chenab Basin",
        "river_name": "Chenab River",
        "lat": 33.1444,
        "lon": 75.5411,
        "catchment_area_km2": 16500.0,
        "slope_deg": 35.0,
        "mean_elevation_m": 2100.0,
        "drainage_density": 2.9,
        "forest_cover_pct": 44.0,
        "bankfull_discharge_m3s": 2800.0,
        "warning_level_m": 7.0,
        "danger_level_m": 9.2,
        "dam_upstream": {
            "name": "Baglihar Dam",
            "rule_curve_threshold": 89.0,
            "capacity_mcm": 396.0,
            "current_storage_pct": 83.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 47,
        "population_at_risk": 72000,
    },
    {
        "id": "kishtwar-marusudar",
        "name": "Kishtwar / Marusudar",
        "state": "Jammu & Kashmir",
        "river_basin": "Indus / Chenab Basin",
        "river_name": "Marusudar / Chenab Confluence",
        "lat": 33.3156,
        "lon": 75.7667,
        "catchment_area_km2": 6100.0,
        "slope_deg": 39.0,
        "mean_elevation_m": 2800.0,
        "drainage_density": 3.4,
        "forest_cover_pct": 48.0,
        "bankfull_discharge_m3s": 1400.0,
        "warning_level_m": 5.2,
        "danger_level_m": 7.1,
        "dam_upstream": {
            "name": "Pakal Dul Dam",
            "rule_curve_threshold": 85.0,
            "capacity_mcm": 125.0,
            "current_storage_pct": 74.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 32,
        "population_at_risk": 39000,
    },
    {
        "id": "poonch-suran",
        "name": "Poonch / Suran River",
        "state": "Jammu & Kashmir",
        "river_basin": "Indus / Jhelum Basin",
        "river_name": "Poonch River",
        "lat": 33.7712,
        "lon": 74.0934,
        "catchment_area_km2": 2100.0,
        "slope_deg": 31.0,
        "mean_elevation_m": 1600.0,
        "drainage_density": 3.1,
        "forest_cover_pct": 52.0,
        "bankfull_discharge_m3s": 850.0,
        "warning_level_m": 4.5,
        "danger_level_m": 6.1,
        "dam_upstream": None,
        "glacier_fed": True,
        "vulnerable_villages": 39,
        "population_at_risk": 58000,
    },
    {
        "id": "leh-indus",
        "name": "Leh (Indus Valley)",
        "state": "Ladakh",
        "river_basin": "Indus Basin",
        "river_name": "Indus River",
        "lat": 34.1526,
        "lon": 77.5771,
        "catchment_area_km2": 31000.0,
        "slope_deg": 26.0,
        "mean_elevation_m": 3850.0,
        "drainage_density": 1.9,
        "forest_cover_pct": 3.0,
        "bankfull_discharge_m3s": 1200.0,
        "warning_level_m": 4.0,
        "danger_level_m": 5.5,
        "dam_upstream": {
            "name": "Nimoo Bazgo HEP",
            "rule_curve_threshold": 88.0,
            "capacity_mcm": 12.0,
            "current_storage_pct": 70.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 29,
        "population_at_risk": 35000,
    },
    {
        "id": "kargil-suru",
        "name": "Kargil (Suru Basin)",
        "state": "Ladakh",
        "river_basin": "Indus Basin",
        "river_name": "Suru River",
        "lat": 34.5539,
        "lon": 76.1311,
        "catchment_area_km2": 4400.0,
        "slope_deg": 33.0,
        "mean_elevation_m": 3300.0,
        "drainage_density": 2.5,
        "forest_cover_pct": 4.0,
        "bankfull_discharge_m3s": 780.0,
        "warning_level_m": 3.8,
        "danger_level_m": 5.2,
        "dam_upstream": {
            "name": "Chutak HEP",
            "rule_curve_threshold": 85.0,
            "capacity_mcm": 5.0,
            "current_storage_pct": 66.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 22,
        "population_at_risk": 28000,
    },

    # ---- 4. Punjab Flood Corridors ----
    {
        "id": "pathankot-madhopur",
        "name": "Pathankot / Madhopur",
        "state": "Punjab",
        "river_basin": "Indus / Ravi Basin",
        "river_name": "Ravi River",
        "lat": 32.2746,
        "lon": 75.6529,
        "catchment_area_km2": 7200.0,
        "slope_deg": 12.0,
        "mean_elevation_m": 380.0,
        "drainage_density": 2.1,
        "forest_cover_pct": 22.0,
        "bankfull_discharge_m3s": 3800.0,
        "warning_level_m": 6.5,
        "danger_level_m": 8.5,
        "dam_upstream": {
            "name": "Ranjit Sagar Dam (Thein)",
            "rule_curve_threshold": 91.0,
            "capacity_mcm": 3280.0,
            "current_storage_pct": 87.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 67,
        "population_at_risk": 115000,
    },
    {
        "id": "ropar-sutlej",
        "name": "Rupnagar / Ropar Headworks",
        "state": "Punjab",
        "river_basin": "Indus / Sutlej Basin",
        "river_name": "Sutlej River",
        "lat": 30.9664,
        "lon": 76.5331,
        "catchment_area_km2": 56800.0,
        "slope_deg": 7.0,
        "mean_elevation_m": 275.0,
        "drainage_density": 1.7,
        "forest_cover_pct": 14.0,
        "bankfull_discharge_m3s": 4500.0,
        "warning_level_m": 7.5,
        "danger_level_m": 9.8,
        "dam_upstream": {
            "name": "Bhakra-Nangal Complex",
            "rule_curve_threshold": 92.0,
            "capacity_mcm": 9621.0,
            "current_storage_pct": 88.5,
        },
        "glacier_fed": True,
        "vulnerable_villages": 82,
        "population_at_risk": 190000,
    },
    {
        "id": "hoshiarpur-choes",
        "name": "Hoshiarpur (Seasonal Choes)",
        "state": "Punjab",
        "river_basin": "Indus / Beas Basin",
        "river_name": "Shivalik Seasonal Torrents",
        "lat": 31.5273,
        "lon": 75.9149,
        "catchment_area_km2": 2800.0,
        "slope_deg": 19.0,
        "mean_elevation_m": 320.0,
        "drainage_density": 3.5,
        "forest_cover_pct": 28.0,
        "bankfull_discharge_m3s": 1350.0,
        "warning_level_m": 4.2,
        "danger_level_m": 6.0,
        "dam_upstream": None,
        "glacier_fed": False,
        "vulnerable_villages": 59,
        "population_at_risk": 84000,
    },
    {
        "id": "gurdaspur-ravi-beas",
        "name": "Gurdaspur (Dera Baba Nanak)",
        "state": "Punjab",
        "river_basin": "Indus / Ravi Basin",
        "river_name": "Ravi River Floodplain",
        "lat": 32.0416,
        "lon": 75.4042,
        "catchment_area_km2": 9500.0,
        "slope_deg": 5.0,
        "mean_elevation_m": 255.0,
        "drainage_density": 1.6,
        "forest_cover_pct": 9.0,
        "bankfull_discharge_m3s": 4200.0,
        "warning_level_m": 6.8,
        "danger_level_m": 8.9,
        "dam_upstream": None,
        "glacier_fed": True,
        "vulnerable_villages": 78,
        "population_at_risk": 140000,
    },
    {
        "id": "firozpur-harike",
        "name": "Firozpur / Harike Wetland",
        "state": "Punjab",
        "river_basin": "Indus Basin",
        "river_name": "Sutlej-Beas Confluence",
        "lat": 31.1572,
        "lon": 74.9622,
        "catchment_area_km2": 82000.0,
        "slope_deg": 3.0,
        "mean_elevation_m": 210.0,
        "drainage_density": 1.4,
        "forest_cover_pct": 8.0,
        "bankfull_discharge_m3s": 6200.0,
        "warning_level_m": 8.2,
        "danger_level_m": 10.5,
        "dam_upstream": {
            "name": "Harike Barrage",
            "rule_curve_threshold": 87.0,
            "capacity_mcm": 85.0,
            "current_storage_pct": 80.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 95,
        "population_at_risk": 230000,
    },
    {
        "id": "fazilka-sutlej-tail",
        "name": "Fazilka (Sutlej Border Reach)",
        "state": "Punjab",
        "river_basin": "Indus / Sutlej Basin",
        "river_name": "Lower Sutlej River",
        "lat": 30.4037,
        "lon": 74.0254,
        "catchment_area_km2": 86000.0,
        "slope_deg": 2.0,
        "mean_elevation_m": 182.0,
        "drainage_density": 1.2,
        "forest_cover_pct": 6.0,
        "bankfull_discharge_m3s": 5800.0,
        "warning_level_m": 7.8,
        "danger_level_m": 9.9,
        "dam_upstream": None,
        "glacier_fed": True,
        "vulnerable_villages": 68,
        "population_at_risk": 120000,
    },
    {
        "id": "amritsar-ubdc",
        "name": "Amritsar / Ajnala",
        "state": "Punjab",
        "river_basin": "Indus / Ravi Basin",
        "river_name": "Ravi River Creek",
        "lat": 31.6340,
        "lon": 74.8723,
        "catchment_area_km2": 4500.0,
        "slope_deg": 4.0,
        "mean_elevation_m": 232.0,
        "drainage_density": 1.5,
        "forest_cover_pct": 7.0,
        "bankfull_discharge_m3s": 2600.0,
        "warning_level_m": 5.4,
        "danger_level_m": 7.2,
        "dam_upstream": None,
        "glacier_fed": False,
        "vulnerable_villages": 51,
        "population_at_risk": 98000,
    },
    {
        "id": "ludhiana-budha-nullah",
        "name": "Ludhiana (Budha Nullah / Sutlej)",
        "state": "Punjab",
        "river_basin": "Indus / Sutlej Basin",
        "river_name": "Sutlej River / Budha Nullah",
        "lat": 30.9010,
        "lon": 75.8573,
        "catchment_area_km2": 61000.0,
        "slope_deg": 4.0,
        "mean_elevation_m": 245.0,
        "drainage_density": 1.5,
        "forest_cover_pct": 6.0,
        "bankfull_discharge_m3s": 4800.0,
        "warning_level_m": 7.0,
        "danger_level_m": 9.2,
        "dam_upstream": None,
        "glacier_fed": True,
        "vulnerable_villages": 73,
        "population_at_risk": 320000,
    },

    # ---- 5. Haryana and Chandigarh ----
    {
        "id": "panchkula-ghaggar",
        "name": "Panchkula / Ghaggar River",
        "state": "Haryana",
        "river_basin": "Ghaggar-Hakra Basin",
        "river_name": "Ghaggar River",
        "lat": 30.6942,
        "lon": 76.8606,
        "catchment_area_km2": 2200.0,
        "slope_deg": 16.0,
        "mean_elevation_m": 365.0,
        "drainage_density": 2.8,
        "forest_cover_pct": 27.0,
        "bankfull_discharge_m3s": 1400.0,
        "warning_level_m": 4.8,
        "danger_level_m": 6.8,
        "dam_upstream": {
            "name": "Kaushalya Dam",
            "rule_curve_threshold": 85.0,
            "capacity_mcm": 35.0,
            "current_storage_pct": 78.0,
        },
        "glacier_fed": False,
        "vulnerable_villages": 45,
        "population_at_risk": 85000,
    },
    {
        "id": "yamunanagar-hathnikund",
        "name": "Yamunanagar / Hathnikund Barrage",
        "state": "Haryana",
        "river_basin": "Ganga / Yamuna Basin",
        "river_name": "Yamuna River",
        "lat": 30.3165,
        "lon": 77.5857,
        "catchment_area_km2": 11200.0,
        "slope_deg": 11.0,
        "mean_elevation_m": 290.0,
        "drainage_density": 2.0,
        "forest_cover_pct": 24.0,
        "bankfull_discharge_m3s": 5800.0,
        "warning_level_m": 7.5,
        "danger_level_m": 9.8,
        "dam_upstream": {
            "name": "Hathnikund Barrage",
            "rule_curve_threshold": 88.0,
            "capacity_mcm": 18.0,
            "current_storage_pct": 82.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 84,
        "population_at_risk": 210000,
    },
    {
        "id": "ambala-tangri",
        "name": "Ambala (Tangri / Markanda)",
        "state": "Haryana",
        "river_basin": "Ghaggar Basin",
        "river_name": "Tangri River",
        "lat": 30.3782,
        "lon": 76.7767,
        "catchment_area_km2": 1850.0,
        "slope_deg": 8.0,
        "mean_elevation_m": 264.0,
        "drainage_density": 2.3,
        "forest_cover_pct": 12.0,
        "bankfull_discharge_m3s": 950.0,
        "warning_level_m": 4.1,
        "danger_level_m": 5.9,
        "dam_upstream": None,
        "glacier_fed": False,
        "vulnerable_villages": 52,
        "population_at_risk": 110000,
    },
    {
        "id": "karnal-yamuna",
        "name": "Karnal / Yamuna Floodplain",
        "state": "Haryana",
        "river_basin": "Ganga / Yamuna Basin",
        "river_name": "Yamuna River",
        "lat": 29.6857,
        "lon": 76.9905,
        "catchment_area_km2": 13500.0,
        "slope_deg": 4.0,
        "mean_elevation_m": 240.0,
        "drainage_density": 1.6,
        "forest_cover_pct": 10.0,
        "bankfull_discharge_m3s": 6200.0,
        "warning_level_m": 7.2,
        "danger_level_m": 9.4,
        "dam_upstream": None,
        "glacier_fed": True,
        "vulnerable_villages": 66,
        "population_at_risk": 145000,
    },
    {
        "id": "chandigarh-sukhna",
        "name": "Chandigarh (Sukhna Catchment)",
        "state": "Chandigarh",
        "river_basin": "Ghaggar Basin",
        "river_name": "Sukhna Choe / N-Choe",
        "lat": 30.7421,
        "lon": 76.8188,
        "catchment_area_km2": 42.0,
        "slope_deg": 22.0,
        "mean_elevation_m": 370.0,
        "drainage_density": 3.8,
        "forest_cover_pct": 62.0,
        "bankfull_discharge_m3s": 220.0,
        "warning_level_m": 3.5,
        "danger_level_m": 4.8,
        "dam_upstream": {
            "name": "Sukhna Lake Regulatory Gates",
            "rule_curve_threshold": 92.0,
            "capacity_mcm": 5.2,
            "current_storage_pct": 89.0,
        },
        "glacier_fed": False,
        "vulnerable_villages": 12,
        "population_at_risk": 48000,
    },

    # ---- 6. Delhi NCT Corridor ----
    {
        "id": "delhi-wazirabad",
        "name": "Delhi (Wazirabad Barrage)",
        "state": "Delhi",
        "river_basin": "Ganga / Yamuna Basin",
        "river_name": "Yamuna River",
        "lat": 28.7118,
        "lon": 77.2346,
        "catchment_area_km2": 19500.0,
        "slope_deg": 2.5,
        "mean_elevation_m": 208.0,
        "drainage_density": 1.4,
        "forest_cover_pct": 11.0,
        "bankfull_discharge_m3s": 7000.0,
        "warning_level_m": 204.5,  # m above MSL
        "danger_level_m": 205.33,
        "dam_upstream": {
            "name": "Wazirabad Barrage Gates",
            "rule_curve_threshold": 90.0,
            "capacity_mcm": 12.0,
            "current_storage_pct": 81.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 38,
        "population_at_risk": 580000,
    },
    {
        "id": "delhi-ito-railway",
        "name": "Delhi (Old Railway Bridge / ITO)",
        "state": "Delhi",
        "river_basin": "Ganga / Yamuna Basin",
        "river_name": "Yamuna River Urban Reach",
        "lat": 28.6631,
        "lon": 77.2483,
        "catchment_area_km2": 20200.0,
        "slope_deg": 2.0,
        "mean_elevation_m": 204.0,
        "drainage_density": 1.3,
        "forest_cover_pct": 8.0,
        "bankfull_discharge_m3s": 7200.0,
        "warning_level_m": 204.5,
        "danger_level_m": 205.33,
        "dam_upstream": None,
        "glacier_fed": True,
        "vulnerable_villages": 42,
        "population_at_risk": 820000,
    },
    {
        "id": "delhi-okhla",
        "name": "Delhi (Okhla Barrage)",
        "state": "Delhi",
        "river_basin": "Ganga / Yamuna Basin",
        "river_name": "Yamuna River / Agra Canal Intake",
        "lat": 28.5447,
        "lon": 77.3112,
        "catchment_area_km2": 21500.0,
        "slope_deg": 2.0,
        "mean_elevation_m": 200.0,
        "drainage_density": 1.3,
        "forest_cover_pct": 10.0,
        "bankfull_discharge_m3s": 7400.0,
        "warning_level_m": 200.0,
        "danger_level_m": 201.2,
        "dam_upstream": {
            "name": "Okhla Barrage",
            "rule_curve_threshold": 88.0,
            "capacity_mcm": 16.0,
            "current_storage_pct": 79.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 35,
        "population_at_risk": 410000,
    },

    # ---- 7. Uttar Pradesh ----
    {
        "id": "saharanpur-hindon",
        "name": "Saharanpur / Hindon River",
        "state": "Uttar Pradesh",
        "river_basin": "Ganga / Yamuna Basin",
        "river_name": "Hindon River",
        "lat": 29.9679,
        "lon": 77.5452,
        "catchment_area_km2": 3200.0,
        "slope_deg": 6.0,
        "mean_elevation_m": 268.0,
        "drainage_density": 2.2,
        "forest_cover_pct": 12.0,
        "bankfull_discharge_m3s": 1100.0,
        "warning_level_m": 4.5,
        "danger_level_m": 6.2,
        "dam_upstream": None,
        "glacier_fed": False,
        "vulnerable_villages": 58,
        "population_at_risk": 130000,
    },
    {
        "id": "lakhimpur-sharda",
        "name": "Lakhimpur Kheri / Sharda",
        "state": "Uttar Pradesh",
        "river_basin": "Ganga / Ghaghra Basin",
        "river_name": "Sharda / Ghaghra River",
        "lat": 27.9463,
        "lon": 80.7788,
        "catchment_area_km2": 18000.0,
        "slope_deg": 4.0,
        "mean_elevation_m": 147.0,
        "drainage_density": 1.5,
        "forest_cover_pct": 21.0,
        "bankfull_discharge_m3s": 6500.0,
        "warning_level_m": 7.8,
        "danger_level_m": 9.7,
        "dam_upstream": {
            "name": "Banbasa Barrage",
            "rule_curve_threshold": 87.0,
            "capacity_mcm": 14.0,
            "current_storage_pct": 83.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 112,
        "population_at_risk": 310000,
    },
    {
        "id": "prayagraj-sangam",
        "name": "Prayagraj (Ganga-Yamuna Confluence)",
        "state": "Uttar Pradesh",
        "river_basin": "Ganga Basin",
        "river_name": "Ganga / Yamuna Confluence",
        "lat": 25.4358,
        "lon": 81.8463,
        "catchment_area_km2": 490000.0,
        "slope_deg": 2.0,
        "mean_elevation_m": 98.0,
        "drainage_density": 1.2,
        "forest_cover_pct": 14.0,
        "bankfull_discharge_m3s": 24000.0,
        "warning_level_m": 84.7,
        "danger_level_m": 85.5,
        "dam_upstream": None,
        "glacier_fed": True,
        "vulnerable_villages": 145,
        "population_at_risk": 680000,
    },
    {
        "id": "varanasi-rajghat",
        "name": "Varanasi / Rajghat",
        "state": "Uttar Pradesh",
        "river_basin": "Ganga Basin",
        "river_name": "Ganga River",
        "lat": 25.3176,
        "lon": 83.0064,
        "catchment_area_km2": 520000.0,
        "slope_deg": 1.8,
        "mean_elevation_m": 76.0,
        "drainage_density": 1.1,
        "forest_cover_pct": 11.0,
        "bankfull_discharge_m3s": 26500.0,
        "warning_level_m": 70.26,
        "danger_level_m": 71.26,
        "dam_upstream": None,
        "glacier_fed": True,
        "vulnerable_villages": 128,
        "population_at_risk": 550000,
    },

    # ---- 8. Rajasthan ----
    {
        "id": "mount-abu-banas",
        "name": "Mount Abu (West Banas)",
        "state": "Rajasthan",
        "river_basin": "West Banas Basin",
        "river_name": "West Banas River",
        "lat": 24.5926,
        "lon": 72.7156,
        "catchment_area_km2": 950.0,
        "slope_deg": 28.0,
        "mean_elevation_m": 1220.0,
        "drainage_density": 2.9,
        "forest_cover_pct": 46.0,
        "bankfull_discharge_m3s": 650.0,
        "warning_level_m": 3.9,
        "danger_level_m": 5.4,
        "dam_upstream": {
            "name": "West Banas Dam",
            "rule_curve_threshold": 85.0,
            "capacity_mcm": 72.0,
            "current_storage_pct": 64.0,
        },
        "glacier_fed": False,
        "vulnerable_villages": 26,
        "population_at_risk": 32000,
    },
    {
        "id": "kota-chambal",
        "name": "Kota / Chambal Barrage",
        "state": "Rajasthan",
        "river_basin": "Ganga / Yamuna Basin",
        "river_name": "Chambal River",
        "lat": 25.1805,
        "lon": 75.8340,
        "catchment_area_km2": 79500.0,
        "slope_deg": 7.0,
        "mean_elevation_m": 271.0,
        "drainage_density": 1.5,
        "forest_cover_pct": 18.0,
        "bankfull_discharge_m3s": 14000.0,
        "warning_level_m": 8.5,
        "danger_level_m": 11.2,
        "dam_upstream": {
            "name": "Kota Barrage / Jawahar Sagar",
            "rule_curve_threshold": 90.0,
            "capacity_mcm": 112.0,
            "current_storage_pct": 82.0,
        },
        "glacier_fed": False,
        "vulnerable_villages": 82,
        "population_at_risk": 290000,
    },

    # ---- 9. High-Vulnerability Western Ghats & North East ----
    {
        "id": "wayanad-kabini",
        "name": "Wayanad (Meppadi / Chooralmala)",
        "state": "Kerala",
        "river_basin": "Cauvery / Kabini & Chaliyar",
        "river_name": "Chaliyar / Iruvanjippuzha Tributaries",
        "lat": 11.6854,
        "lon": 76.1320,
        "catchment_area_km2": 2130.0,
        "slope_deg": 41.5,
        "mean_elevation_m": 980.0,
        "drainage_density": 3.7,
        "forest_cover_pct": 68.0,
        "bankfull_discharge_m3s": 920.0,
        "warning_level_m": 4.6,
        "danger_level_m": 6.4,
        "dam_upstream": {
            "name": "Banasura Sagar Dam (Earth Dam)",
            "rule_curve_threshold": 87.0,
            "capacity_mcm": 209.0,
            "current_storage_pct": 84.0,
        },
        "glacier_fed": False,
        "vulnerable_villages": 36,
        "population_at_risk": 62000,
    },
    {
        "id": "idukki-periyar",
        "name": "Idukki (Cheruthoni Gorge)",
        "state": "Kerala",
        "river_basin": "Periyar Basin",
        "river_name": "Periyar River",
        "lat": 9.8500,
        "lon": 76.9800,
        "catchment_area_km2": 5100.0,
        "slope_deg": 38.0,
        "mean_elevation_m": 1200.0,
        "drainage_density": 3.3,
        "forest_cover_pct": 74.0,
        "bankfull_discharge_m3s": 2400.0,
        "warning_level_m": 6.2,
        "danger_level_m": 8.1,
        "dam_upstream": {
            "name": "Idukki Double-Curvature Arch Dam",
            "rule_curve_threshold": 92.0,
            "capacity_mcm": 1996.0,
            "current_storage_pct": 88.0,
        },
        "glacier_fed": False,
        "vulnerable_villages": 49,
        "population_at_risk": 98000,
    },
    {
        "id": "teesta-mangan",
        "name": "Teesta / Mangan (Chungthang Basin)",
        "state": "Sikkim",
        "river_basin": "Brahmaputra / Teesta Basin",
        "river_name": "Teesta River / Lachen / Lachung",
        "lat": 27.5080,
        "lon": 88.5284,
        "catchment_area_km2": 3950.0,
        "slope_deg": 46.0,
        "mean_elevation_m": 3650.0,
        "drainage_density": 3.9,
        "forest_cover_pct": 54.0,
        "bankfull_discharge_m3s": 1450.0,
        "warning_level_m": 5.4,
        "danger_level_m": 7.3,
        "dam_upstream": {
            "name": "Teesta III HEP (Chungthang GLOF site)",
            "rule_curve_threshold": 80.0,
            "capacity_mcm": 5.0,
            "current_storage_pct": 76.0,
        },
        "glacier_fed": True,
        "vulnerable_villages": 31,
        "population_at_risk": 41000,
    },
    {
        "id": "dima-hasao-barak",
        "name": "Dima Hasao / Haflong Hills",
        "state": "Assam",
        "river_basin": "Barak Basin",
        "river_name": "Jatinga / Barak Tributary",
        "lat": 25.1764,
        "lon": 93.0238,
        "catchment_area_km2": 4890.0,
        "slope_deg": 33.0,
        "mean_elevation_m": 680.0,
        "drainage_density": 3.1,
        "forest_cover_pct": 76.0,
        "bankfull_discharge_m3s": 1800.0,
        "warning_level_m": 5.8,
        "danger_level_m": 7.6,
        "dam_upstream": {
            "name": "Khandong Dam (Kopili HEP)",
            "rule_curve_threshold": 86.0,
            "capacity_mcm": 166.0,
            "current_storage_pct": 81.0,
        },
        "glacier_fed": False,
        "vulnerable_villages": 57,
        "population_at_risk": 74000,
    },
    {
        "id": "cherrapunji-sohra",
        "name": "Cherrapunji / Sohra Canyons",
        "state": "Meghalaya",
        "river_basin": "Meghalaya South Slope Basin",
        "river_name": "Wah Umngot / Shella River",
        "lat": 25.2986,
        "lon": 91.7322,
        "catchment_area_km2": 820.0,
        "slope_deg": 48.0,
        "mean_elevation_m": 1290.0,
        "drainage_density": 4.2,
        "forest_cover_pct": 63.0,
        "bankfull_discharge_m3s": 1600.0,
        "warning_level_m": 4.9,
        "danger_level_m": 6.8,
        "dam_upstream": None,
        "glacier_fed": False,
        "vulnerable_villages": 28,
        "population_at_risk": 38000,
    },
]

# Quick lookup by id
REGIONS_BY_ID: Dict[str, Dict[str, Any]] = {r["id"]: r for r in REGIONS}
